// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AddTag struct {
	ImageID string `json:"imageId"`
	TagID   string `json:"tagId"`
}

type Image struct {
	ImageDataID *string         `json:"imageDataId"`
	File        *graphql.Upload `json:"file"`
}

type ImageData struct {
	ID   string  `json:"id"`
	URI  string  `json:"uri"`
	Name *string `json:"name"`
	Tags []*Tag  `json:"tags"`
}

type NewImageData struct {
	Name *string `json:"name"`
}

type NewTag struct {
	Name  string  `json:"name"`
	Color *string `json:"color"`
}

type Tag struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Color *string `json:"color"`
}
